
CREATE TABLE fournisseur (
	ID int(11) AUTO_INCREMENT PRIMARY KEY,
    NOM varchar(25)
);
CREATE TABLE article(
	ID int(11) AUTO_INCREMENT PRIMARY KEY,
    REF varchar(13),
    DESIGNATION varchar(255),
    PRIX decimal(7.2),
    ID_FOU int(11)
);
CREATE TABLE bon(
    ID int(11) AUTO_INCREMENT PRIMARY KEY,
    NUMERO int(11),
    DATE_CMDE datetime,
    DELAI int(11),
    IDFOU int(11)
);
CREATE TABLE compo(
	ID int(11) AUTO_INCREMENT PRIMARY KEY,
    ID_ART int(11),
    ID_BON int(11),
    QTE int(11)
);
ALTER table bon CHANGE IDFOU ID_FOU int(11);
ALTER TABLE article ADD CONSTRAINT FOREIGN KEY (ID_FOU) REFERENCES fournisseurs(ID);
ALTER TABLE bon ADD CONSTRAINT FOREIGN KEY (ID_FOU) REFERENCES fournisseurs(ID);
ALTER TABLE compo ADD CONSTRAINT FOREIGN KEY (ID_BON) REFERENCES bon(ID);
ALTER TABLE compo ADD CONSTRAINT FOREIGN KEY (ID_ART) REFERENCES article(ID);